CENTRAL_PARK_BRANCH = "Central Park Library"
CENTRAL_PARK_BRANCH_CODE = "C"
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
EMBEDDING_PATH = "embeddings.npy"
EMBEDDING_MIDS_PATH = "embedding_mids.json"
TIME_DECAY_HALF_LIFE_DAYS = 90
TOP_CANDIDATES = 25
MMR_LAMBDA = 0.5
MMR_TOP_K = 100
FILTER_ENGLISH = True
AVAILABILITY_CACHE_SECONDS = 900

UPDATE_WINDOW_START = 2     # 2 AM
UPDATE_WINDOW_END = 4       # 4 AM
UPDATE_DAILY_INTERVAL_HOURS = 24
UPDATE_CATALOG_INTERVAL_HOURS = 168
