CENTRAL_PARK_BRANCH = "Central Park Library"
CENTRAL_PARK_BRANCH_CODE = "C"
TFIDF_MAX_FEATURES = 10000
TIME_DECAY_HALF_LIFE_DAYS = 90
TOP_CANDIDATES = 50
MMR_LAMBDA = 0.5
CHECKOUTS_PARALLEL_WORKERS = 10
FILTER_HOME_BRANCH = True
FILTER_ENGLISH = True
AVAILABILITY_CACHE_SECONDS = 900

UPDATE_WINDOW_START = 2     # 2 AM
UPDATE_WINDOW_END = 4       # 4 AM
UPDATE_DAILY_INTERVAL_HOURS = 24
UPDATE_CATALOG_INTERVAL_HOURS = 168
